/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PgInMaladEastRouteImport } from './routes/pg-in-malad-east'
import { Route as PgInMaladRouteImport } from './routes/pg-in-malad'
import { Route as PgInJogeshwariRouteImport } from './routes/pg-in-jogeshwari'
import { Route as PgInGoregaonRouteImport } from './routes/pg-in-goregaon'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesSlugRouteImport } from './routes/properties.$slug'
import { Route as LocationsSlugRouteImport } from './routes/locations.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PgInMaladEastRoute = PgInMaladEastRouteImport.update({
  id: '/pg-in-malad-east',
  path: '/pg-in-malad-east',
  getParentRoute: () => rootRouteImport,
} as any)
const PgInMaladRoute = PgInMaladRouteImport.update({
  id: '/pg-in-malad',
  path: '/pg-in-malad',
  getParentRoute: () => rootRouteImport,
} as any)
const PgInJogeshwariRoute = PgInJogeshwariRouteImport.update({
  id: '/pg-in-jogeshwari',
  path: '/pg-in-jogeshwari',
  getParentRoute: () => rootRouteImport,
} as any)
const PgInGoregaonRoute = PgInGoregaonRouteImport.update({
  id: '/pg-in-goregaon',
  path: '/pg-in-goregaon',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesSlugRoute = PropertiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PropertiesRoute,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/locations': typeof LocationsRouteWithChildren
  '/pg-in-goregaon': typeof PgInGoregaonRoute
  '/pg-in-jogeshwari': typeof PgInJogeshwariRoute
  '/pg-in-malad': typeof PgInMaladRoute
  '/pg-in-malad-east': typeof PgInMaladEastRoute
  '/privacy': typeof PrivacyRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/locations': typeof LocationsRouteWithChildren
  '/pg-in-goregaon': typeof PgInGoregaonRoute
  '/pg-in-jogeshwari': typeof PgInJogeshwariRoute
  '/pg-in-malad': typeof PgInMaladRoute
  '/pg-in-malad-east': typeof PgInMaladEastRoute
  '/privacy': typeof PrivacyRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/locations': typeof LocationsRouteWithChildren
  '/pg-in-goregaon': typeof PgInGoregaonRoute
  '/pg-in-jogeshwari': typeof PgInJogeshwariRoute
  '/pg-in-malad': typeof PgInMaladRoute
  '/pg-in-malad-east': typeof PgInMaladEastRoute
  '/privacy': typeof PrivacyRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/locations'
    | '/pg-in-goregaon'
    | '/pg-in-jogeshwari'
    | '/pg-in-malad'
    | '/pg-in-malad-east'
    | '/privacy'
    | '/properties'
    | '/sitemap.xml'
    | '/terms'
    | '/locations/$slug'
    | '/properties/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/locations'
    | '/pg-in-goregaon'
    | '/pg-in-jogeshwari'
    | '/pg-in-malad'
    | '/pg-in-malad-east'
    | '/privacy'
    | '/properties'
    | '/sitemap.xml'
    | '/terms'
    | '/locations/$slug'
    | '/properties/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/locations'
    | '/pg-in-goregaon'
    | '/pg-in-jogeshwari'
    | '/pg-in-malad'
    | '/pg-in-malad-east'
    | '/privacy'
    | '/properties'
    | '/sitemap.xml'
    | '/terms'
    | '/locations/$slug'
    | '/properties/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LocationsRoute: typeof LocationsRouteWithChildren
  PgInGoregaonRoute: typeof PgInGoregaonRoute
  PgInJogeshwariRoute: typeof PgInJogeshwariRoute
  PgInMaladRoute: typeof PgInMaladRoute
  PgInMaladEastRoute: typeof PgInMaladEastRoute
  PrivacyRoute: typeof PrivacyRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pg-in-malad-east': {
      id: '/pg-in-malad-east'
      path: '/pg-in-malad-east'
      fullPath: '/pg-in-malad-east'
      preLoaderRoute: typeof PgInMaladEastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pg-in-malad': {
      id: '/pg-in-malad'
      path: '/pg-in-malad'
      fullPath: '/pg-in-malad'
      preLoaderRoute: typeof PgInMaladRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pg-in-jogeshwari': {
      id: '/pg-in-jogeshwari'
      path: '/pg-in-jogeshwari'
      fullPath: '/pg-in-jogeshwari'
      preLoaderRoute: typeof PgInJogeshwariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pg-in-goregaon': {
      id: '/pg-in-goregaon'
      path: '/pg-in-goregaon'
      fullPath: '/pg-in-goregaon'
      preLoaderRoute: typeof PgInGoregaonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$slug': {
      id: '/properties/$slug'
      path: '/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof PropertiesSlugRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof LocationsRoute
    }
  }
}

interface LocationsRouteChildren {
  LocationsSlugRoute: typeof LocationsSlugRoute
}

const LocationsRouteChildren: LocationsRouteChildren = {
  LocationsSlugRoute: LocationsSlugRoute,
}

const LocationsRouteWithChildren = LocationsRoute._addFileChildren(
  LocationsRouteChildren,
)

interface PropertiesRouteChildren {
  PropertiesSlugRoute: typeof PropertiesSlugRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesSlugRoute: PropertiesSlugRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LocationsRoute: LocationsRouteWithChildren,
  PgInGoregaonRoute: PgInGoregaonRoute,
  PgInJogeshwariRoute: PgInJogeshwariRoute,
  PgInMaladRoute: PgInMaladRoute,
  PgInMaladEastRoute: PgInMaladEastRoute,
  PrivacyRoute: PrivacyRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
